CONNECTORS = [
    "MySQL",
    "PostgreSQL",
]

# Types not supported, not displayed in Multiplexer settings for selection
NON_SUPPORTED_TYPES = [
    "ARReport",
    "ARTemplates",
    "ATBooleanCriterion",
    "ATCurrentAuthorCriterion",
    "ATDateCriteria",
    "ATDateRangeCriterion",
    "ATListCriterion",
    "ATPathCriterion",
    "ATPortalTypeCriterion",
    "ATReferenceCriterion",
    "ATRelativePathCriterion",
    "ATSelectionCriterion",
    "ATSimpleIntCriterion",
    "ATSimpleStringCriterion",
    "ATSortCriterion",
    "AetiologicAgents",
    "AnalysisCategories",
    "AnalysisProfiles",
    "AnalysisRequestsFolder",
    "AnalysisServices",
    "AnalysisSpecs",
    "Attachment",
    "AttachmentTypes",
    "AuditLog",
    "AutoImportLog",
    "BatchFolder",
    "BatchLabels",
    "BikaSetup",
    "Calculations",
    "CaseOutcomes",
    "CaseStatuses",
    "CaseSyndromicClassifications",
    "ClientFolder",
    "Collection",
    "ContainerTypes",
    "Containers",
    "DataBox",
    "DataBoxFolder",
    "Departments",
    "Diseases",
    "Doctors",
    "Document",
    "DrugProhibitions",
    "Drugs",
    "DynamicAnalysisSpecs",
    "Ethnicities",
    "Event",
    "File",
    "Folder",
    "IdentifierTypes",
    "Image",
    "Immunizations",
    "InstrumentCalibration",
    "InstrumentLocations",
    "InstrumentTypes",
    "Instruments",
    "InsuranceCompanies",
    "LabContacts",
    "LabProducts",
    "Laboratory",
    "Link",
    "Manufacturers",
    "Multifile",
    "Methods",
    "News Item",
    "Patients",
    "Plone Site",
    "Preservations",
    "PricelistFolder",
    "ReferenceDefinitions",
    "ReferenceSamplesFolder",
    "ReflexRuleFolder",
    "RejectAnalysis",
    "ReportFolder",
    "Sample",
    "SampleConditions",
    "SampleMatrices",
    "SamplePartition",
    "SamplePoints",
    "SampleTypes",
    "SamplingDeviations",
    "StorageLocations",
    "StorageRootFolder",
    "StorageSamplesContainer",
    "SubGroups",
    "SupplierContact",
    "Suppliers",
    "SupplyOrderFolder",
    "Symptoms",
    "TempFolder",
    "Topic",
    "Treatments",
    "VaccinationCenterContact",
    "VaccinationCenters",
    "WorksheetFolder",
    "WorksheetTemplates",
]

# List of non supported fields
NON_SUPPORTED_FIELD_TYPES = [
    "file",
    "computed",
    "remarks",
    "specifications",
]

NON_SUPPORTED_FIELD_NAMES = [
    "allowedRolesAndUsers",
    "allowDiscussion",
    "constrainTypesMode",
    "contributor",
    "contributors",
    "creators",
    "effectiveDate",
    "excludeFromNav",
    "expirationDate",
    "immediatelyAddableTypes",
    "language",
    "locallyAllowedTypes",
    "location",
    "nextPreviousEnabled",
    "rights",
    "subject",
]

NON_SUPPORTED_FIELDS_BY_PORTAL_TYPE = (
    ("AnalysisRequest", [
        "Attachment",
        "_ARAttachment",
        "Invoice",
        "Analyses",
    ]),
    ("Batch", [
        "BatchID",
    ]),
)

OTHER_FIELDS = (
    ("Analysis", [
        "FormattedResult",
    ]),
)

CUSTOM_TYPES = (
    ("Analysis", {
        "Result": "text",
    }),
)
